---
   - name: Configure Elk VM with Docker
     hosts: elkservers
     become: true
     tasks:
    
     - name: Install docker.io
       apt:
         name: docker.io
         update_cache: yes
         state: present

     - name: Install Python3-pip
       apt:
         name: python3-pip
         state: present

     - name: Install Docker using pip
       pip:
         name: docker
         state: present
 
     - name: Use more memory
       sysctl:
         name: vm.max_map_count
         value: "262144"
         state: present
         reload: yes

     - name: Install ELK
       docker_container:
         name: ELK
         image: sebp/elk:761
         restart_policy: always
         state: started
         published_ports:
           - 5601:5601
           - 9200:9200
           - 5044:5044
        
     - name: Enable docker service on restart
       systemd:
         name: docker
         enabled: yes

