---
  - name: My first playbook
    hosts: webservers
    become: true
    tasks:

    - name: download filebeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: install filebeat deb
      command: dpkg -i filebeat-7.6.1-amd64.deb

    - name: drop in filebeat.yml 
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: enable and configure system module
      command: filebeat modules enable system

    - name: setup filebeat
      command: filebeat setup

    - name: start filebeat service
      command: service filebeat start
root@62f16005c8ed:~# cat metricbeat-playbook.yml 
---
  - name: Install and Launch Metricbeat
    hosts: webservers
    become: yes
    tasks:
    # Use command module
    - name: Download metricbeat .deb metric
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
    # Use command module
    - name: Install metricbeat .deb
      command: dpkg -i metricbeat-7.6.1-amd64.deb
    # Use copy module
    - name: Copy over and drop in metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml
    # Use command module
    - name: Enable and Configure Docker Module
      command: metricbeat modules enable docker
    # Use command module
    - name: Setup metricbeat
      command: metricbeat setup
    # Use command module
    - name: Start metricbeat service
      command: service metricbeat start

